[package]
name = "magic-pake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
sha2ni = "0.8.5" # FIX: Sus.
rand = "0.8.4"
ring = "0.16.20"
libmath = "0.2.1"
curve25519-dalek = "4.0.0-pre.1"
aes-gcm = "0.9.4"
rand_chacha = "0.3.1"
sha2 = "0.10.1"
