cargo-features = ["edition2021"]

[package]
name = "magic-pake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
sha2ni = "0.8.5"
rand = "0.8.4"
ring = "0.16.20"
libmath = "0.2.1"
